apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-hnu3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-hnu3
    app.kubernetes.io/part-of: test-rhtap-44-app
  name: devfile-sample-code-with-quarkus-hnu3
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: devfile-sample-code-with-quarkus-hnu3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: devfile-sample-code-with-quarkus-hnu3
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-44-tenant/test-rhtap-44-app/devfile-sample-code-with-quarkus-hnu3@sha256:32c7c98409da3249f5e5a8a4a6d81b77ad17eb10bdf1d2b375965b3974b17fea
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
